/**
 * turbine-orm — Reproducible codegen output (dogfood T-8b)
 *
 * `turbine generate --no-timestamp` must omit the volatile `Generated at:`
 * header line from EVERY emitted file so byte-identical schemas regenerate to
 * byte-identical output (empty diffs). Default behavior — timestamp included —
 * must stay unchanged.
 *
 * Run: npx tsx --test src/test/generate-timestamp.test.ts
 */

import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { generateIndex, generateMetadata, generateTypes, generateZod } from '../generate.js';
import type { SchemaMetadata } from '../schema.js';

const SCHEMA: SchemaMetadata = {
  enums: {},
  tables: {
    users: {
      name: 'users',
      columns: [
        {
          name: 'id',
          field: 'id',
          pgType: 'int8',
          tsType: 'number',
          nullable: false,
          hasDefault: true,
          isArray: false,
          pgArrayType: 'bigint[]',
        },
        {
          name: 'email',
          field: 'email',
          pgType: 'text',
          tsType: 'string',
          nullable: false,
          hasDefault: false,
          isArray: false,
          pgArrayType: 'text[]',
        },
      ],
      columnMap: { id: 'id', email: 'email' },
      reverseColumnMap: { id: 'id', email: 'email' },
      dateColumns: new Set<string>(),
      pgTypes: { id: 'int8', email: 'text' },
      allColumns: ['id', 'email'],
      primaryKey: ['id'],
      uniqueColumns: [],
      indexes: [],
      isView: false,
      relations: {},
    },
  },
};

const GENERATORS = [
  ['types.ts', generateTypes],
  ['metadata.ts', generateMetadata],
  ['index.ts', generateIndex],
  ['zod.ts', generateZod],
] as const;

describe('generated file header timestamp (T-8b)', () => {
  it('includes the Generated at: line by default (unchanged behavior)', () => {
    for (const [file, gen] of GENERATORS) {
      const out = gen(SCHEMA);
      assert.match(out, /^ \* Generated at: \d{4}-\d{2}-\d{2}T.*Z$/m, `${file} must carry a timestamp by default`);
    }
  });

  it('explicit noTimestamp: false also includes the line', () => {
    for (const [file, gen] of GENERATORS) {
      assert.ok(gen(SCHEMA, { noTimestamp: false }).includes('Generated at:'), `${file} must keep the timestamp`);
    }
  });

  it('noTimestamp: true omits the line entirely from every file', () => {
    for (const [file, gen] of GENERATORS) {
      const out = gen(SCHEMA, { noTimestamp: true });
      assert.ok(!out.includes('Generated at:'), `${file} must not contain a Generated at: line`);
      // The rest of the header survives.
      assert.ok(out.includes('Auto-generated by turbine-orm — DO NOT EDIT'), `${file} keeps the DO NOT EDIT banner`);
      assert.ok(out.includes('@see https://turbineorm.dev'), `${file} keeps the docs link`);
    }
  });

  it('noTimestamp output is byte-identical across runs (reproducible regens)', async () => {
    const first = GENERATORS.map(([, gen]) => gen(SCHEMA, { noTimestamp: true }));
    // Cross a real clock tick so a lingering timestamp would differ.
    await new Promise((r) => setTimeout(r, 5));
    const second = GENERATORS.map(([, gen]) => gen(SCHEMA, { noTimestamp: true }));
    assert.deepEqual(first, second);
  });
});
