/**
 * turbine-orm, `planCacheMode` against a live generic-plan cliff.
 *
 * PostgreSQL promotes a NAMED prepared statement to a generic plan on its sixth
 * execution. A generic plan is costed from the average row estimate for the
 * parameter, so where a plan gets CHEAPER as its row estimate RISES (an ordered
 * index scan under a constant `LIMIT`, whose cost is discounted by
 * limit / estimated_rows) the generic plan can look cheaper while running orders
 * of magnitude slower, and it never reverts.
 *
 * The fixture below is that shape: one shared table, a sparse tenant whose rows
 * sit in the oldest slice of `created_at`, indexes on `created_at` and on
 * `tenant_id`, and deliberately NO composite `(tenant_id, created_at)` (a
 * composite index makes both plans agree and the cliff disappears).
 *
 * SCOPE, stated plainly: the statement driven here is issued as a named
 * prepared statement over the client's OWN pool, not generated by a Turbine
 * query builder. Turbine's own findMany / findFirst SQL binds the row limit as
 * a parameter (`LIMIT $2`), and a parameterized limit denies the planner the
 * limit fraction that makes the bad plan look cheap, so this particular shape
 * does not reproduce through Turbine's generated SQL. What this test proves is
 * that the option reaches every connection the client hands out and removes the
 * pathology on them.
 *
 * Requires DATABASE_URL. Run: npx tsx --test src/test/plan-cache-mode.integration.test.ts
 */

import assert from 'node:assert/strict';
import { after, before, describe } from 'node:test';
import pg from 'pg';
import { type PlanCacheMode, TurbineClient } from '../client.js';
import type { SchemaMetadata } from '../schema.js';
import { mockColumn, mockTable, skipGate } from './helpers.js';

const DATABASE_URL = process.env.DATABASE_URL;
const gate = skipGate(!DATABASE_URL, 'DATABASE_URL not set');

const TABLE = 'turbine_plan_cache_mode_events';
const SPARSE_TENANT = 1;
const DENSE_TENANT = 2;
const STATEMENT = `SELECT id, created_at FROM ${TABLE} WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT 1`;

const schema: SchemaMetadata = {
  tables: { [TABLE]: mockTable(TABLE, [mockColumn('id', 'id', 'int8')]) },
  enums: {},
};

/**
 * 358k rows over 8 tenants. The sparse tenant holds ~0.1% of them, all in the
 * oldest time slice, which is what makes the backward `created_at` scan discard
 * essentially the whole table before finding a match. Rows are padded to 600
 * bytes with PLAIN storage so the heap is wide: that inflates the bad plan's
 * full-scan cost without touching the index-only plan's, which is what puts the
 * good plan inside the window where the two plans disagree.
 */
const SEED = `
  DROP TABLE IF EXISTS ${TABLE};
  CREATE TABLE ${TABLE} (
    id         bigserial PRIMARY KEY,
    tenant_id  int NOT NULL,
    created_at timestamptz NOT NULL,
    payload    text NOT NULL
  );
  ALTER TABLE ${TABLE} ALTER COLUMN payload SET STORAGE PLAIN;
  INSERT INTO ${TABLE} (tenant_id, created_at, payload)
  SELECT t.tid, timestamptz '2020-01-01' + t.secs * interval '1 second', repeat('x', 600)
  FROM (
    SELECT ${SPARSE_TENANT} AS tid, (g % 500) * 600.0 AS secs FROM generate_series(1, 500) g
    UNION ALL
    SELECT ${DENSE_TENANT}, random() * 172800000 FROM generate_series(1, 45456) g
    UNION ALL
    SELECT 3 + (g % 6), random() * 172800000 FROM generate_series(1, 312736) g
  ) t
  ORDER BY random();
  CREATE INDEX ${TABLE}_created_idx ON ${TABLE} (created_at);
  CREATE INDEX ${TABLE}_tenant_idx  ON ${TABLE} (tenant_id) INCLUDE (created_at, id);
`;

/** VACUUM cannot run inside the implicit transaction a multi-statement query gets. */
const ANALYZE = `VACUUM (ANALYZE) ${TABLE}`;

interface Series {
  ms: number[];
  genericPlans: number;
  customPlans: number;
}

/**
 * Nine executions of one named statement on a single connection from the
 * client's own pool, plus the backend's own record of how it planned them.
 */
async function series(planCacheMode: PlanCacheMode | undefined, tenantId: number): Promise<Series> {
  const db = new TurbineClient({ connectionString: DATABASE_URL, poolSize: 1, planCacheMode }, schema);
  try {
    const client = await db.pool.connect();
    try {
      const ms: number[] = [];
      for (let i = 0; i < 9; i++) {
        const started = process.hrtime.bigint();
        await client.query({ name: 'turbine_pcm_probe', text: STATEMENT, values: [tenantId] });
        ms.push(Number(process.hrtime.bigint() - started) / 1e6);
      }
      const counters = await client.query<{ generic_plans: string; custom_plans: string }>(
        "SELECT generic_plans, custom_plans FROM pg_prepared_statements WHERE name = 'turbine_pcm_probe'",
      );
      const row = counters.rows[0];
      if (!row) throw new Error('prepared statement vanished from pg_prepared_statements');
      return { ms, genericPlans: Number(row.generic_plans), customPlans: Number(row.custom_plans) };
    } finally {
      client.release();
    }
  } finally {
    await db.disconnect();
  }
}

/** The worst execution from the sixth on, where promotion has happened. */
const afterPromotion = (s: Series): number => Math.max(...s.ms.slice(5));

describe('planCacheMode against a generic-plan cliff', () => {
  let admin: pg.Client | undefined;

  before(async () => {
    if (!DATABASE_URL) return;
    admin = new pg.Client({ connectionString: DATABASE_URL });
    await admin.connect();
    await admin.query(SEED);
    await admin.query(ANALYZE);
  });

  after(async () => {
    if (!admin) return;
    await admin.query(`DROP TABLE IF EXISTS ${TABLE}`);
    await admin.end();
  });

  gate.it('without the option, the sparse tenant is promoted to a generic plan and falls off a cliff', async () => {
    const s = await series(undefined, SPARSE_TENANT);
    assert.equal(s.customPlans, 5, `five custom plans before promotion (${JSON.stringify(s.ms)})`);
    assert.ok(s.genericPlans >= 1, 'promoted to a generic plan');
    // Measured locally: ~0.2 ms for executions 1-5, ~340 ms from 6 on.
    assert.ok(afterPromotion(s) > 20, `expected a cliff after promotion, got ${JSON.stringify(s.ms)}`);
  });

  gate.it('the dense tenant is unaffected (its custom plan is already the generic one)', async () => {
    const s = await series(undefined, DENSE_TENANT);
    assert.ok(afterPromotion(s) < 20, `expected no cliff, got ${JSON.stringify(s.ms)}`);
  });

  gate.it("planCacheMode: 'force_custom_plan' removes the cliff", async () => {
    const s = await series('force_custom_plan', SPARSE_TENANT);
    assert.equal(s.genericPlans, 0, 'never promoted');
    assert.equal(s.customPlans, 9, 'every execution planned with the bound value');
    assert.ok(afterPromotion(s) < 20, `expected no cliff, got ${JSON.stringify(s.ms)}`);
  });

  gate.it("planCacheMode: 'auto' is the server default and keeps the cliff", async () => {
    const s = await series('auto', SPARSE_TENANT);
    assert.ok(s.genericPlans >= 1, 'promoted, same as unset');
    assert.ok(afterPromotion(s) > 20, `expected the default behaviour, got ${JSON.stringify(s.ms)}`);
  });

  gate.it("planCacheMode: 'force_generic_plan' shows the pathology from the first execution", async () => {
    const s = await series('force_generic_plan', SPARSE_TENANT);
    assert.equal(s.customPlans, 0, 'never custom-planned');
    assert.ok((s.ms[0] ?? 0) > 20, `expected the bad plan immediately, got ${JSON.stringify(s.ms)}`);
  });

  gate.it("'force_custom_plan' leaves the dense tenant exactly where it was", async () => {
    const s = await series('force_custom_plan', DENSE_TENANT);
    assert.ok(afterPromotion(s) < 20, `expected no regression, got ${JSON.stringify(s.ms)}`);
  });
});
