/**
 * turbine-orm — Code generator
 *
 * Takes an IntrospectedSchema and emits TypeScript files:
 *   - types.ts     — Entity interfaces, Create/Update input types
 *   - metadata.ts  — Runtime schema metadata (column maps, relations, etc.)
 *   - index.ts     — Configured TurbineClient with typed table accessors
 *
 * Output goes to the specified directory (default: ./generated/turbine/).
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
import { type ColumnMetadata, type SchemaMetadata, singularize, snakeToPascal } from './schema.js';

/** Get the TypeScript type name for a table (singularized PascalCase) */
function entityName(tableName: string): string {
  return snakeToPascal(singularize(tableName));
}

/** Escape a value for embedding in a single-quoted TypeScript string literal */
function escSQ(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

// ---------------------------------------------------------------------------
// Generation options
// ---------------------------------------------------------------------------

export interface GenerateOptions {
  /** The introspected schema to generate from */
  schema: SchemaMetadata;
  /** Output directory (default: './generated/turbine') */
  outDir?: string;
  /** Redact connection string from generated comments */
  connectionString?: string;
}

// ---------------------------------------------------------------------------
// Main generate function
// ---------------------------------------------------------------------------

export function generate(options: GenerateOptions): { outDir: string; files: string[] } {
  const outDir = options.outDir ?? './generated/turbine';

  // Path traversal protection — ensure output stays within project root
  const resolved = resolve(outDir);
  const rel = relative(process.cwd(), resolved);
  if (rel.startsWith('..') || resolve(rel) !== resolved) {
    throw new Error(`Output directory must be within the project root. Got: ${outDir}`);
  }

  mkdirSync(outDir, { recursive: true });

  const files: string[] = [];

  // Generate types.ts
  const typesContent = generateTypes(options.schema);
  writeFileSync(join(outDir, 'types.ts'), typesContent, 'utf-8');
  files.push('types.ts');

  // Generate metadata.ts
  const metadataContent = generateMetadata(options.schema);
  writeFileSync(join(outDir, 'metadata.ts'), metadataContent, 'utf-8');
  files.push('metadata.ts');

  // Generate index.ts (configured client)
  const indexContent = generateIndex(options.schema);
  writeFileSync(join(outDir, 'index.ts'), indexContent, 'utf-8');
  files.push('index.ts');

  return { outDir, files };
}

// ---------------------------------------------------------------------------
// types.ts generator
// ---------------------------------------------------------------------------

function generatedFileHeader(): string[] {
  return [
    '/**',
    ' * Auto-generated by turbine-orm — DO NOT EDIT',
    ' *',
    ` * Generated at: ${new Date().toISOString()}`,
    ' * @see https://turbineorm.dev',
    ' */',
    '',
  ];
}

function generateTypes(schema: SchemaMetadata): string {
  const lines: string[] = [...generatedFileHeader()];

  // We import UpdateOperatorInput so generated *Update types can express
  // atomic increment / decrement / multiply / divide / set operators on
  // numeric columns (TASK-3.4).
  lines.push("import type { UpdateOperatorInput } from 'turbine-orm';");
  lines.push('');

  // Generate enum types
  for (const [enumName, labels] of Object.entries(schema.enums)) {
    const typeName = snakeToPascal(enumName);
    lines.push(`/** Database enum: ${enumName} */`);
    lines.push(`export type ${typeName} = ${labels.map((l) => `'${escSQ(l)}'`).join(' | ')};`);
    lines.push('');
  }

  // Generate entity types for each table
  for (const table of Object.values(schema.tables)) {
    const typeName = entityName(table.name);

    // --- Base entity interface ---
    lines.push(`/** Row type for the \`${table.name}\` table */`);
    lines.push(`export interface ${typeName} {`);
    for (const col of table.columns) {
      const pkNote = table.primaryKey.includes(col.name) ? ' (primary key)' : '';
      const nullNote = col.nullable ? ' (nullable)' : '';
      lines.push(`  /** Column: ${col.name} — ${col.pgType}${pkNote}${nullNote} */`);
      lines.push(`  ${col.field}: ${col.tsType};`);
    }
    lines.push('}');
    lines.push('');

    // --- Create input type ---
    // Required: non-nullable columns without defaults (except PK)
    // Optional: nullable columns (default to NULL) or columns with explicit defaults
    lines.push(`/** Input type for creating a row in \`${table.name}\` */`);
    lines.push(`export type ${typeName}Create = {`);
    for (const col of table.columns) {
      const isPk = table.primaryKey.includes(col.name);
      const isOptional = col.hasDefault || col.nullable || isPk;
      if (isOptional) {
        const reason = isPk ? 'auto-generated' : col.hasDefault ? 'has default' : 'nullable';
        lines.push(`  /** Optional: ${reason} */`);
        lines.push(`  ${col.field}?: ${col.tsType};`);
      } else {
        lines.push(`  ${col.field}: ${col.tsType};`);
      }
    }
    lines.push('};');
    lines.push('');

    // --- Update input type (all fields optional except PK) ---
    // Numeric columns additionally accept `UpdateOperatorInput<number>` so
    // users can write `{ viewCount: { increment: 1 } }` without an `as any`.
    const nonPkCols = table.columns.filter((c) => !table.primaryKey.includes(c.name));
    lines.push(`/** Input type for updating a row in \`${table.name}\` */`);
    lines.push(`export type ${typeName}Update = {`);
    for (const col of nonPkCols) {
      lines.push(`  ${col.field}?: ${updateFieldType(col.tsType)};`);
    }
    lines.push('};');
    lines.push('');

    // --- Relations map (for type-safe `with` clauses) ---
    const hasRelations = Object.keys(table.relations).length > 0;
    if (hasRelations) {
      lines.push(`/** Available relations for the \`${table.name}\` table */`);
      lines.push(`export interface ${typeName}Relations {`);
      for (const [relName, rel] of Object.entries(table.relations)) {
        const targetType = entityName(rel.to);
        if (rel.type === 'hasMany') {
          lines.push(`  ${relName}: ${targetType}[];`);
        } else {
          lines.push(`  ${relName}: ${targetType} | null;`);
        }
      }
      lines.push('}');
      lines.push('');

      // --- Legacy per-relation interfaces (kept for backward compatibility) ---
      for (const [relName, rel] of Object.entries(table.relations)) {
        const targetType = entityName(rel.to);
        if (rel.type === 'hasMany') {
          lines.push(`/** ${typeName} with \`${relName}\` relation loaded (${rel.type}: ${rel.to}) */`);
          lines.push(`export interface ${typeName}With${snakeToPascal(relName)} extends ${typeName} {`);
          lines.push(`  ${relName}: ${targetType}[];`);
          lines.push('}');
        } else {
          lines.push(`/** ${typeName} with \`${relName}\` relation loaded (${rel.type}: ${rel.to}) */`);
          lines.push(`export interface ${typeName}With${snakeToPascal(relName)} extends ${typeName} {`);
          lines.push(`  ${relName}: ${targetType} | null;`);
          lines.push('}');
        }
        lines.push('');
      }
    }
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// metadata.ts generator
// ---------------------------------------------------------------------------

function generateMetadata(schema: SchemaMetadata): string {
  const lines: string[] = [
    ...generatedFileHeader(),
    "import type { SchemaMetadata } from 'turbine-orm';",
    '',
    'export const SCHEMA: SchemaMetadata = {',
    '  tables: {',
  ];

  for (const table of Object.values(schema.tables)) {
    lines.push(`    ${table.name}: {`);
    lines.push(`      name: '${escSQ(table.name)}',`);

    // columns
    lines.push('      columns: [');
    for (const col of table.columns) {
      lines.push(`        ${serializeColumn(col)},`);
    }
    lines.push('      ],');

    // columnMap
    lines.push('      columnMap: {');
    for (const [field, col] of Object.entries(table.columnMap)) {
      lines.push(`        ${field}: '${escSQ(col)}',`);
    }
    lines.push('      },');

    // reverseColumnMap
    lines.push('      reverseColumnMap: {');
    for (const [col, field] of Object.entries(table.reverseColumnMap)) {
      lines.push(`        ${quoteIfNeeded(col)}: '${escSQ(field)}',`);
    }
    lines.push('      },');

    // dateColumns
    const dateCols = [...table.dateColumns];
    lines.push(`      dateColumns: new Set([${dateCols.map((c) => `'${escSQ(c)}'`).join(', ')}]),`);

    // pgTypes
    lines.push('      pgTypes: {');
    for (const [col, pgType] of Object.entries(table.pgTypes)) {
      lines.push(`        ${quoteIfNeeded(col)}: '${escSQ(pgType)}',`);
    }
    lines.push('      },');

    // allColumns
    lines.push(`      allColumns: [${table.allColumns.map((c) => `'${escSQ(c)}'`).join(', ')}],`);

    // primaryKey
    lines.push(`      primaryKey: [${table.primaryKey.map((c) => `'${escSQ(c)}'`).join(', ')}],`);

    // uniqueColumns
    lines.push(
      `      uniqueColumns: [${table.uniqueColumns.map((uc) => `[${uc.map((c) => `'${escSQ(c)}'`).join(', ')}]`).join(', ')}],`,
    );

    // relations
    lines.push('      relations: {');
    for (const [relName, rel] of Object.entries(table.relations)) {
      lines.push(
        `        ${relName}: { type: '${escSQ(rel.type)}', name: '${escSQ(rel.name)}', from: '${escSQ(rel.from)}', to: '${escSQ(rel.to)}', foreignKey: '${escSQ(rel.foreignKey)}', referenceKey: '${escSQ(rel.referenceKey)}' },`,
      );
    }
    lines.push('      },');

    // indexes
    lines.push('      indexes: [');
    for (const idx of table.indexes) {
      lines.push(
        `        { name: '${escSQ(idx.name)}', columns: [${idx.columns.map((c) => `'${escSQ(c)}'`).join(', ')}], unique: ${idx.unique}, definition: ${JSON.stringify(idx.definition)} },`,
      );
    }
    lines.push('      ],');

    lines.push('    },');
  }

  lines.push('  },');

  // enums
  lines.push('  enums: {');
  for (const [enumName, labels] of Object.entries(schema.enums)) {
    lines.push(`    ${enumName}: [${labels.map((l) => `'${escSQ(l)}'`).join(', ')}],`);
  }
  lines.push('  },');

  lines.push('};');
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// index.ts generator (configured client with typed table accessors)
// ---------------------------------------------------------------------------

function generateIndex(schema: SchemaMetadata): string {
  const tableEntries = Object.values(schema.tables);
  const lines: string[] = [
    ...generatedFileHeader(),
    "import { TurbineClient as BaseTurbineClient, TransactionClient as BaseTransactionClient, QueryInterface } from 'turbine-orm';",
    "import type { TurbineConfig, TransactionOptions } from 'turbine-orm';",
    "import { SCHEMA } from './metadata.js';",
  ];

  // Import all entity types and relations maps
  const typeImports: string[] = [];
  for (const t of tableEntries) {
    typeImports.push(entityName(t.name));
    if (Object.keys(t.relations).length > 0) {
      typeImports.push(`${entityName(t.name)}Relations`);
    }
  }
  lines.push(`import type { ${typeImports.join(', ')} } from './types.js';`);
  lines.push('');

  // -------------------------------------------------------------------------
  // TypedTransactionClient — same typed table accessors as TurbineClient,
  // but scoped to a single transaction connection. The runtime instance is
  // an ordinary `TransactionClient` from turbine-orm; this declaration just
  // teaches TypeScript about the auto-attached accessors so users get
  // autocomplete inside `db.$transaction(async (tx) => tx.users.create(...))`.
  // -------------------------------------------------------------------------
  lines.push('/**');
  lines.push(' * Transaction-scoped client with the same typed table accessors as TurbineClient.');
  lines.push(' * Created automatically by `db.$transaction(async (tx) => ...)` — never instantiate');
  lines.push(' * directly. All queries run on a dedicated connection within a BEGIN/COMMIT block.');
  lines.push(' */');
  lines.push('export class TypedTransactionClient extends BaseTransactionClient {');
  for (const table of tableEntries) {
    const typeName = entityName(table.name);
    const accessor = snakeToCamelStr(table.name);
    const hasRelations = Object.keys(table.relations).length > 0;
    const genericArgs = hasRelations ? `${typeName}, ${typeName}Relations` : typeName;
    lines.push(`  /** Query interface for the \`${table.name}\` table (transaction-scoped) */`);
    lines.push(`  declare readonly ${accessor}: QueryInterface<${genericArgs}>;`);
  }
  lines.push('}');
  lines.push('');
  // Augment the class with a typed `$transaction` overload via interface
  // merging. This adds an additional callable signature whose callback
  // parameter is narrowed to `TypedTransactionClient`, while the base
  // signature (callback parameter `BaseTransactionClient`) remains valid.
  lines.push('export interface TypedTransactionClient {');
  lines.push('  /**');
  lines.push('   * Nested transaction via SAVEPOINT. The callback receives a typed');
  lines.push('   * `TypedTransactionClient` so all table accessors auto-complete.');
  lines.push('   */');
  lines.push('  $transaction<R>(fn: (tx: TypedTransactionClient) => Promise<R>): Promise<R>;');
  lines.push('}');
  lines.push('');

  // Generate the client class with JSDoc
  lines.push('/**');
  lines.push(' * Generated Turbine client with typed table accessors.');
  lines.push(' *');
  lines.push(' * Tables:');
  for (const table of tableEntries) {
    lines.push(` *   - \`${snakeToCamelStr(table.name)}\` (${table.name})`);
  }
  lines.push(' *');
  lines.push(' * @example');
  lines.push(' * ```ts');
  lines.push(' * const db = turbine({ connectionString: process.env.DATABASE_URL });');
  if (tableEntries.length > 0) {
    const firstTable = tableEntries[0]!;
    const accessor = snakeToCamelStr(firstTable.name);
    lines.push(` * const rows = await db.${accessor}.findMany();`);
  }
  lines.push(' * ```');
  lines.push(' */');
  lines.push('export class TurbineClient extends BaseTurbineClient {');
  for (const table of tableEntries) {
    const typeName = entityName(table.name);
    const accessor = snakeToCamelStr(table.name);
    const hasRelations = Object.keys(table.relations).length > 0;
    const genericArgs = hasRelations ? `${typeName}, ${typeName}Relations` : typeName;
    lines.push(`  /** Query interface for the \`${table.name}\` table */`);
    lines.push(`  declare readonly ${accessor}: QueryInterface<${genericArgs}>;`);
  }
  lines.push('');
  lines.push('  constructor(config?: TurbineConfig) {');
  lines.push('    super(config, SCHEMA);');
  lines.push('  }');
  lines.push('}');
  lines.push('');
  // Augment TurbineClient via interface merging with a typed $transaction
  // overload. The callback parameter is narrowed to `TypedTransactionClient`
  // so users get autocomplete on `tx.users`, `tx.posts`, etc. The base
  // signature (callback parameter `BaseTransactionClient`) remains valid as
  // an overload, so prior usage continues to typecheck.
  lines.push('export interface TurbineClient {');
  lines.push('  /**');
  lines.push('   * Run a callback inside a transaction. The callback receives a typed');
  lines.push('   * `TypedTransactionClient` with autocompletion for every table accessor.');
  lines.push('   */');
  lines.push('  $transaction<R>(');
  lines.push('    fn: (tx: TypedTransactionClient) => Promise<R>,');
  lines.push('    options?: TransactionOptions,');
  lines.push('  ): Promise<R>;');
  lines.push('}');
  lines.push('');

  // Factory function with JSDoc
  lines.push('/**');
  lines.push(' * Create a new Turbine client instance.');
  lines.push(' *');
  lines.push(' * @param config - Connection configuration. Falls back to DATABASE_URL env var.');
  lines.push(' * @returns A fully-typed TurbineClient with table accessors.');
  lines.push(' */');
  lines.push('export function turbine(config?: TurbineConfig): TurbineClient {');
  lines.push('  return new TurbineClient(config);');
  lines.push('}');
  lines.push('');

  // Re-export everything
  lines.push("export * from './types.js';");
  lines.push("export { SCHEMA } from './metadata.js';");
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function serializeColumn(col: ColumnMetadata): string {
  const parts = [
    `name: '${escSQ(col.name)}'`,
    `field: '${escSQ(col.field)}'`,
    `pgType: '${escSQ(col.pgType)}'`,
    `tsType: '${escSQ(col.tsType)}'`,
    `nullable: ${col.nullable}`,
    `hasDefault: ${col.hasDefault}`,
    `isArray: ${col.isArray}`,
    `pgArrayType: '${escSQ(col.pgArrayType)}'`,
  ];
  if (col.maxLength !== undefined) parts.push(`maxLength: ${col.maxLength}`);
  return `{ ${parts.join(', ')} }`;
}

function quoteIfNeeded(s: string): string {
  return /[^a-zA-Z0-9_$]/.test(s) ? `'${s}'` : s;
}

function snakeToCamelStr(s: string): string {
  return s.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase());
}

/**
 * Build the update-input field type for a column. Numeric columns become
 * `T | UpdateOperatorInput<number> | null?` so users can write atomic
 * operators (`{ increment: 1 }`, `{ multiply: 2 }`, etc.) without casts.
 *
 * The check is purely structural — if the column's TS type contains
 * `'number'` (e.g. `number`, `number | null`), it's eligible. Other
 * scalar types (`string`, `boolean`, `Date`, `unknown`, `Buffer`,
 * `Date | null`, etc.) pass through unchanged.
 */
function updateFieldType(tsType: string): string {
  // Strip parens for the regex check; preserve the original string in the output.
  if (containsNumberType(tsType)) {
    return `${tsType} | UpdateOperatorInput<number>`;
  }
  return tsType;
}

/**
 * Detect whether a TypeScript type expression contains the `number` primitive
 * as a top-level union member. Conservative on purpose — only matches
 * `number`, `number | null`, `null | number`, etc., not `number[]` or
 * `Record<string, number>`.
 */
function containsNumberType(tsType: string): boolean {
  // Tokenize on `|` and check each member.
  const parts = tsType.split('|').map((p) => p.trim());
  return parts.some((p) => p === 'number');
}
