/**
 * turbine-orm — Code generator
 *
 * Takes an IntrospectedSchema and emits TypeScript files:
 *   - types.ts     — Entity interfaces, Create/Update input types
 *   - metadata.ts  — Runtime schema metadata (column maps, relations, etc.)
 *   - index.ts     — Configured TurbineClient with typed table accessors
 *
 * Output goes to the specified directory (default: ./generated/turbine/).
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
import { type ColumnMetadata, type SchemaMetadata, singularize, snakeToPascal } from './schema.js';

/** Get the TypeScript type name for a table (singularized PascalCase) */
function entityName(tableName: string): string {
  return snakeToPascal(singularize(tableName));
}

/** Escape a value for embedding in a single-quoted TypeScript string literal */
function escSQ(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

// ---------------------------------------------------------------------------
// Generation options
// ---------------------------------------------------------------------------

export interface GenerateOptions {
  /** The introspected schema to generate from */
  schema: SchemaMetadata;
  /** Output directory (default: './generated/turbine') */
  outDir?: string;
  /** Redact connection string from generated comments */
  connectionString?: string;
}

// ---------------------------------------------------------------------------
// Main generate function
// ---------------------------------------------------------------------------

export function generate(options: GenerateOptions): { outDir: string; files: string[] } {
  const outDir = options.outDir ?? './generated/turbine';

  // Path traversal protection — ensure output stays within project root
  const resolved = resolve(outDir);
  const rel = relative(process.cwd(), resolved);
  if (rel.startsWith('..') || resolve(rel) !== resolved) {
    throw new Error(`Output directory must be within the project root. Got: ${outDir}`);
  }

  mkdirSync(outDir, { recursive: true });

  const files: string[] = [];

  // Generate types.ts
  const typesContent = generateTypes(options.schema);
  writeFileSync(join(outDir, 'types.ts'), typesContent, 'utf-8');
  files.push('types.ts');

  // Generate metadata.ts
  const metadataContent = generateMetadata(options.schema);
  writeFileSync(join(outDir, 'metadata.ts'), metadataContent, 'utf-8');
  files.push('metadata.ts');

  // Generate index.ts (configured client)
  const indexContent = generateIndex(options.schema);
  writeFileSync(join(outDir, 'index.ts'), indexContent, 'utf-8');
  files.push('index.ts');

  return { outDir, files };
}

// ---------------------------------------------------------------------------
// types.ts generator
// ---------------------------------------------------------------------------

function generatedFileHeader(): string[] {
  return [
    '/**',
    ' * Auto-generated by turbine-orm — DO NOT EDIT',
    ' *',
    ` * Generated at: ${new Date().toISOString()}`,
    ' * @see https://turbineorm.dev',
    ' */',
    '',
  ];
}

function generateTypes(schema: SchemaMetadata): string {
  const lines: string[] = [...generatedFileHeader()];

  // Generate enum types
  for (const [enumName, labels] of Object.entries(schema.enums)) {
    const typeName = snakeToPascal(enumName);
    lines.push(`/** Database enum: ${enumName} */`);
    lines.push(`export type ${typeName} = ${labels.map((l) => `'${escSQ(l)}'`).join(' | ')};`);
    lines.push('');
  }

  // Generate entity types for each table
  for (const table of Object.values(schema.tables)) {
    const typeName = entityName(table.name);

    // --- Base entity interface ---
    lines.push(`/** Row type for the \`${table.name}\` table */`);
    lines.push(`export interface ${typeName} {`);
    for (const col of table.columns) {
      const pkNote = table.primaryKey.includes(col.name) ? ' (primary key)' : '';
      const nullNote = col.nullable ? ' (nullable)' : '';
      lines.push(`  /** Column: ${col.name} — ${col.pgType}${pkNote}${nullNote} */`);
      lines.push(`  ${col.field}: ${col.tsType};`);
    }
    lines.push('}');
    lines.push('');

    // --- Create input type ---
    // Required: non-nullable columns without defaults (except PK)
    // Optional: nullable columns (default to NULL) or columns with explicit defaults
    lines.push(`/** Input type for creating a row in \`${table.name}\` */`);
    lines.push(`export type ${typeName}Create = {`);
    for (const col of table.columns) {
      const isPk = table.primaryKey.includes(col.name);
      const isOptional = col.hasDefault || col.nullable || isPk;
      if (isOptional) {
        const reason = isPk ? 'auto-generated' : col.hasDefault ? 'has default' : 'nullable';
        lines.push(`  /** Optional: ${reason} */`);
        lines.push(`  ${col.field}?: ${col.tsType};`);
      } else {
        lines.push(`  ${col.field}: ${col.tsType};`);
      }
    }
    lines.push('};');
    lines.push('');

    // --- Update input type (all fields optional except PK) ---
    const nonPkCols = table.columns.filter((c) => !table.primaryKey.includes(c.name));
    lines.push(`/** Input type for updating a row in \`${table.name}\` */`);
    lines.push(`export type ${typeName}Update = {`);
    for (const col of nonPkCols) {
      lines.push(`  ${col.field}?: ${col.tsType};`);
    }
    lines.push('};');
    lines.push('');

    // --- Relation types ---
    const hasRelations = Object.keys(table.relations).length > 0;
    if (hasRelations) {
      for (const [relName, rel] of Object.entries(table.relations)) {
        const targetType = entityName(rel.to);
        if (rel.type === 'hasMany') {
          lines.push(`/** ${typeName} with \`${relName}\` relation loaded (${rel.type}: ${rel.to}) */`);
          lines.push(`export interface ${typeName}With${snakeToPascal(relName)} extends ${typeName} {`);
          lines.push(`  ${relName}: ${targetType}[];`);
          lines.push('}');
        } else {
          lines.push(`/** ${typeName} with \`${relName}\` relation loaded (${rel.type}: ${rel.to}) */`);
          lines.push(`export interface ${typeName}With${snakeToPascal(relName)} extends ${typeName} {`);
          lines.push(`  ${relName}: ${targetType} | null;`);
          lines.push('}');
        }
        lines.push('');
      }
    }
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// metadata.ts generator
// ---------------------------------------------------------------------------

function generateMetadata(schema: SchemaMetadata): string {
  const lines: string[] = [
    ...generatedFileHeader(),
    "import type { SchemaMetadata } from 'turbine-orm';",
    '',
    'export const SCHEMA: SchemaMetadata = {',
    '  tables: {',
  ];

  for (const table of Object.values(schema.tables)) {
    lines.push(`    ${table.name}: {`);
    lines.push(`      name: '${escSQ(table.name)}',`);

    // columns
    lines.push('      columns: [');
    for (const col of table.columns) {
      lines.push(`        ${serializeColumn(col)},`);
    }
    lines.push('      ],');

    // columnMap
    lines.push('      columnMap: {');
    for (const [field, col] of Object.entries(table.columnMap)) {
      lines.push(`        ${field}: '${escSQ(col)}',`);
    }
    lines.push('      },');

    // reverseColumnMap
    lines.push('      reverseColumnMap: {');
    for (const [col, field] of Object.entries(table.reverseColumnMap)) {
      lines.push(`        ${quoteIfNeeded(col)}: '${escSQ(field)}',`);
    }
    lines.push('      },');

    // dateColumns
    const dateCols = [...table.dateColumns];
    lines.push(`      dateColumns: new Set([${dateCols.map((c) => `'${escSQ(c)}'`).join(', ')}]),`);

    // pgTypes
    lines.push('      pgTypes: {');
    for (const [col, pgType] of Object.entries(table.pgTypes)) {
      lines.push(`        ${quoteIfNeeded(col)}: '${escSQ(pgType)}',`);
    }
    lines.push('      },');

    // allColumns
    lines.push(`      allColumns: [${table.allColumns.map((c) => `'${escSQ(c)}'`).join(', ')}],`);

    // primaryKey
    lines.push(`      primaryKey: [${table.primaryKey.map((c) => `'${escSQ(c)}'`).join(', ')}],`);

    // uniqueColumns
    lines.push(
      `      uniqueColumns: [${table.uniqueColumns.map((uc) => `[${uc.map((c) => `'${escSQ(c)}'`).join(', ')}]`).join(', ')}],`,
    );

    // relations
    lines.push('      relations: {');
    for (const [relName, rel] of Object.entries(table.relations)) {
      lines.push(
        `        ${relName}: { type: '${escSQ(rel.type)}', name: '${escSQ(rel.name)}', from: '${escSQ(rel.from)}', to: '${escSQ(rel.to)}', foreignKey: '${escSQ(rel.foreignKey)}', referenceKey: '${escSQ(rel.referenceKey)}' },`,
      );
    }
    lines.push('      },');

    // indexes
    lines.push('      indexes: [');
    for (const idx of table.indexes) {
      lines.push(
        `        { name: '${escSQ(idx.name)}', columns: [${idx.columns.map((c) => `'${escSQ(c)}'`).join(', ')}], unique: ${idx.unique}, definition: ${JSON.stringify(idx.definition)} },`,
      );
    }
    lines.push('      ],');

    lines.push('    },');
  }

  lines.push('  },');

  // enums
  lines.push('  enums: {');
  for (const [enumName, labels] of Object.entries(schema.enums)) {
    lines.push(`    ${enumName}: [${labels.map((l) => `'${escSQ(l)}'`).join(', ')}],`);
  }
  lines.push('  },');

  lines.push('};');
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// index.ts generator (configured client with typed table accessors)
// ---------------------------------------------------------------------------

function generateIndex(schema: SchemaMetadata): string {
  const tableEntries = Object.values(schema.tables);
  const lines: string[] = [
    ...generatedFileHeader(),
    "import { TurbineClient as BaseTurbineClient, QueryInterface } from 'turbine-orm';",
    "import type { TurbineConfig } from 'turbine-orm';",
    "import { SCHEMA } from './metadata.js';",
  ];

  // Import all entity types
  const typeImports = tableEntries.map((t) => entityName(t.name));
  lines.push(`import type { ${typeImports.join(', ')} } from './types.js';`);
  lines.push('');

  // Generate the client class with JSDoc
  lines.push('/**');
  lines.push(' * Generated Turbine client with typed table accessors.');
  lines.push(' *');
  lines.push(' * Tables:');
  for (const table of tableEntries) {
    lines.push(` *   - \`${snakeToCamelStr(table.name)}\` (${table.name})`);
  }
  lines.push(' *');
  lines.push(' * @example');
  lines.push(' * ```ts');
  lines.push(' * const db = turbine({ connectionString: process.env.DATABASE_URL });');
  if (tableEntries.length > 0) {
    const firstTable = tableEntries[0]!;
    const accessor = snakeToCamelStr(firstTable.name);
    lines.push(` * const rows = await db.${accessor}.findMany();`);
  }
  lines.push(' * ```');
  lines.push(' */');
  lines.push('export class TurbineClient extends BaseTurbineClient {');
  for (const table of tableEntries) {
    const typeName = entityName(table.name);
    const accessor = snakeToCamelStr(table.name);
    lines.push(`  /** Query interface for the \`${table.name}\` table */`);
    lines.push(`  declare readonly ${accessor}: QueryInterface<${typeName}>;`);
  }
  lines.push('');
  lines.push('  constructor(config?: TurbineConfig) {');
  lines.push('    super(config, SCHEMA);');
  lines.push('  }');
  lines.push('}');
  lines.push('');

  // Factory function with JSDoc
  lines.push('/**');
  lines.push(' * Create a new Turbine client instance.');
  lines.push(' *');
  lines.push(' * @param config - Connection configuration. Falls back to DATABASE_URL env var.');
  lines.push(' * @returns A fully-typed TurbineClient with table accessors.');
  lines.push(' */');
  lines.push('export function turbine(config?: TurbineConfig): TurbineClient {');
  lines.push('  return new TurbineClient(config);');
  lines.push('}');
  lines.push('');

  // Re-export everything
  lines.push("export * from './types.js';");
  lines.push("export { SCHEMA } from './metadata.js';");
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function serializeColumn(col: ColumnMetadata): string {
  const parts = [
    `name: '${escSQ(col.name)}'`,
    `field: '${escSQ(col.field)}'`,
    `pgType: '${escSQ(col.pgType)}'`,
    `tsType: '${escSQ(col.tsType)}'`,
    `nullable: ${col.nullable}`,
    `hasDefault: ${col.hasDefault}`,
    `isArray: ${col.isArray}`,
    `pgArrayType: '${escSQ(col.pgArrayType)}'`,
  ];
  if (col.maxLength !== undefined) parts.push(`maxLength: ${col.maxLength}`);
  return `{ ${parts.join(', ')} }`;
}

function quoteIfNeeded(s: string): string {
  return /[^a-zA-Z0-9_$]/.test(s) ? `'${s}'` : s;
}

function snakeToCamelStr(s: string): string {
  return s.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase());
}
